# Generated by Django 5.1.1 on 2024-09-15 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_remove_gallery_photo_gallery_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
    ]
