# Generated by Django 5.1.1 on 2024-09-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Team Member Name')),
                ('title', models.CharField(max_length=255, verbose_name='Team Member Title')),
                ('thumbnail', models.ImageField(upload_to='team_thumbnails/', verbose_name='Profile Image')),
                ('description', models.TextField(verbose_name='Team Member Description')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ('name',),
            },
        ),
    ]
