# Generated by Django 5.1.1 on 2024-09-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_blog_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_coching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
