# Generated by Django 5.1.1 on 2024-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_about_coching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_coching',
            name='description',
            field=models.TextField(),
        ),
    ]
