# Generated by Django 5.1.1 on 2024-09-05 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_course_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.course'),
        ),
    ]
