# Generated by Django 5.1.1 on 2024-09-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
