# Generated by Django 5.1.1 on 2024-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_faq_faq_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq_details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
